# Generated by Django 5.0.2 on 2025-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartaddition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено покупателем'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено продавцом'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('seller_confirmed', 'Подтверждено продавцом'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
