# Generated by Django 5.1.1 on 2025-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_payment_confirmed_order_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена в тенге', max_digits=10),
        ),
    ]
