# Generated by Django 5.0.2 on 2025-06-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supportcategory_remove_cartaddition_added_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения оплаты'), ('paid', 'Оплачен'), ('seller_confirmed', 'Подтверждено продавцом'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('not_received', 'Не получен')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на тикет',
                'verbose_name_plural': 'Ответы на тикеты',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SupportTicketResponse',
        ),
    ]
