# Generated by Django 5.0.2 on 2025-06-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_status_supportticketreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supportticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='supportticketreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportArticle',
        ),
        migrations.DeleteModel(
            name='SupportCategory',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='SupportTicketReply',
        ),
    ]
